# Prework Assignment

### General Background Questions

1. Why is version control important in science?

In [1]:
# Reproducibility improved for science
# more detailed record of work
# facilitate collaboration
# help peer review
# record key process, prevent key mistakes

2. What kind of research artifacts can we track with Git?

In [1]:
# manuscripts and notes: track versions and highlight changes in notes
# datasets: help the collecting and restoring process
# statistical code and figures: revert back the changes

3. What are the three main things that can go wrong in a data science project?

In [1]:
# 1. some wanted data do not exist or it isn't stored in a usable way, expectation vs reality
# 2. data not fit the prediction, or data is right, model is wrong
# 3. Proposed solution does not solve the right problem, if there is in fact a problem in the first place

### Python Background Questions

These short exercises are a way to familiarize yourself with python. If you find these exercises too difficult, don’t worry! We will review the basics the first day to make sure we are all comfortable coding in Python.

Please save your work in this document and `git push` them to the `prework-assignment` repo.

----------------------------------------------------------------

### Problem 1: Basic Operations

You are at Vanessa's Vegan Cafe and you loved it so much you wanna leave a tip. Write a function that takes the amount owed and calculates how much money you pay with an 18% tip. If functions still scare you, just the solution code will do.

In [5]:
def money_calc(amount):
    return amount*1.18

money_calc(1)

1.18

----------------------------------------------------------------

### Problem 2: Lists

I have a fortune cookie that says my lucky numbers are:

       [23, 54, 6, 8, 10078, 3]

Write a function that returns 3 lists (if functions still scare you, just the solution code will do)
   - replace the number 6 with 1
   - the above list in decreasing order
   - all values greater than 15

In [4]:
def list_modi():
    #initializations
    list1 = [23, 54, 6, 8, 10078, 3]
    list2 = list1.copy()
    list3 = []

    #modificaitons
    list1[2] = 1
    list2.sort(reverse = True)
    for i in list1:
        if i > 15:
            list3.append(i)
    return list1, list2, list3

----------------------------------------------------------------

### Problem 3: Basic Operations

Let's now take the first step in coding some real data science. Write a statement that loads the `numpy` library into the interpreter and gives it an alias of `np`.

In [3]:
# your code here
import numpy as np

----------------------------------------------------------------

### Problem 4: Numpy

Generated a 10x10 `numpy` array with random numbers and slice the array to get the 2nd and 3rd column. Also calculate the average of 6th column using `numpy`.

In [14]:
arr = np.random.randint(10, size=(10, 10))
arr

array([[7, 1, 2, 1, 1, 4, 7, 9, 9, 4],
       [7, 6, 6, 4, 8, 5, 3, 6, 3, 4],
       [5, 7, 2, 1, 7, 8, 0, 2, 4, 0],
       [0, 6, 7, 8, 2, 4, 2, 6, 2, 6],
       [3, 6, 4, 9, 3, 9, 9, 6, 3, 8],
       [2, 9, 8, 0, 7, 7, 3, 5, 5, 2],
       [9, 5, 3, 0, 4, 8, 8, 5, 1, 3],
       [1, 0, 8, 0, 5, 3, 4, 3, 8, 9],
       [9, 1, 4, 8, 9, 6, 3, 2, 4, 0],
       [8, 8, 9, 6, 0, 3, 9, 5, 6, 4]])

In [15]:
arr[:, 1:3]

array([[1, 2],
       [6, 6],
       [7, 2],
       [6, 7],
       [6, 4],
       [9, 8],
       [5, 3],
       [0, 8],
       [1, 4],
       [8, 9]])

In [23]:
total = 0
for i in arr[:, 5:6]:
    total += i
total/10

array([5.7])

----------------------------------------------------------------

##### That's it! We look forward to seeing you in class!